version: '3.6'

services:
  web:
    build:
      context: .
    volumes:
      - ./reactweb:/var/www
      - /var/www/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
      - "4000:4000"
